services:
  rmbg-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped