FROM huggingface/transformers-pytorch-gpu:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/models
ENV HF_HOME=/app/models

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]