services:
  rmbg-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped